jQuery(document).on("ready", function () {
    jQuery(window)
        .on("resize", function () {
            jQuery(window).width() < 520 && jQuery(window).width() > 300
                ? ($(".slideContent").attr("data-hoffset", "-230"),
                  $(".slideContent").attr("data-y", "200"),
                  $(".slideImg").attr("style", "width: 100vw !important;height:auto !important;"),
                  $(".badgeSize").attr("style", "width:80vw !important;"),
                  $(".fa-check").attr("style", " font-size: 0.5rem;"),
                  $(".caption1").attr("data-x", "550"),
                  $(".text12").attr("data-x", "550"),
                  $(".caption2").attr("data-x", "550"),
                  $(".caption3").attr("data-x", "550"),
                  $(".caption4").attr("data-x", "550"),
                  $(".caption3").attr("data-voffset", "-100"),
                  $(".regBadge1").attr("data-y", "350"),
                  $(".regBadge2").attr("data-y", "410"),
                  $(".regBadge2").attr("data-x", "550"),
                  $(".regBadge3").attr("data-x", "550"),
                  $(".regBadge4").attr("data-x", "550"),
                  $(".regBadge4").attr("data-y", "300"))
                : jQuery(window).width() < 800 && jQuery(window).width() > 520
                ? ($(".slideContent").attr("data-hoffset", "-190"),
                  $(".slideContent").attr("data-y", "200"),
                  $(".slideImg").attr("style", "width: 80vw !important;height:auto !important;"),
                  $(".badgeSize").attr("style", "width:50vw !important;"),
                  $(".fa-check").attr("style", " font-size: 0.5rem;"),
                  $(".caption1").attr("data-x", "550"),
                  $(".text12").attr("data-x", "550"),
                  $(".caption2").attr("data-x", "550"),
                  $(".caption3").attr("data-x", "550"),
                  $(".caption4").attr("data-x", "550"),
                  $(".caption3").attr("data-voffset", "-100"),
                  $(".regBadge1").attr("data-y", "350"),
                  $(".regBadge2").attr("data-y", "410"),
                  $(".regBadge2").attr("data-x", "550"),
                  $(".regBadge3").attr("data-x", "550"),
                  $(".regBadge4").attr("data-x", "550"),
                  $(".regBadge4").attr("data-y", "300"))
                : jQuery(window).width() < 900 && jQuery(window).width() > 800
                ? ($(".slideContent").attr("data-hoffset", "-200"),
                  $(".slideContent").attr("data-y", "200"),
                  $(".slideImg").attr("style", "width: 80vw !important;height:auto !important;"),
                  $(".badgeSize").attr("style", "width:20vw !important;"),
                  $(".fa-check").attr("style", " font-size: 0.5rem;"),
                  $(".caption1").attr("data-x", "550"),
                  $(".text12").attr("data-x", "550"),
                  $(".caption2").attr("data-x", "550"),
                  $(".caption3").attr("data-x", "550"),
                  $(".caption4").attr("data-x", "550"),
                  $(".caption3").attr("data-voffset", "-100"),
                  $(".regBadge1").attr("data-y", "350"),
                  $(".regBadge2").attr("data-y", "410"),
                  $(".regBadge2").attr("data-x", "550"),
                  $(".regBadge3").attr("data-x", "550"),
                  $(".regBadge4").attr("data-x", "550"),
                  $(".regBadge4").attr("data-y", "300"))
                : jQuery(window).width() < 1030 && jQuery(window).width() > 900
                ? ($(".slideContent").attr("data-hoffset", "-120"),
                  $(".slideImg").attr("style", "width: 55vw !important;height:auto !important;"),
                  $(".badgeSize").attr("style", "width:20vw !important;"),
                  $(".caption1").attr("data-x", "600"),
                  $(".caption2").attr("data-x", "600"),
                  $(".caption3").attr("data-x", "600"),
                  $(".caption4").attr("data-x", "600"),
                  $(".caption3").attr("data-voffset", "-100"),
                  $(".regBadge2").attr("data-y", "400"),
                  $(".regBadge2").attr("data-x", "610"),
                  $(".regBadge3").attr("data-x", "610"),
                  $(".regBadge4").attr("data-x", "620"),
                  $(".regBadge4").attr("data-y", "280"))
                : jQuery(window).width() < 1290 && jQuery(window).width() >= 1030
                ? ($(".slideContent").attr("data-hoffset", "-150"),
                  $(".slideImg").attr("style", "width: 49vw !important;height:auto !important;"),
                  $(".badgeSize").attr("style", "width:20vw !important;"),
                  $(".caption1").attr("data-x", "620"),
                  $(".caption2").attr("data-x", "620"),
                  $(".caption3").attr("data-x", "620"),
                  $(".caption4").attr("data-x", "620"),
                  $(".text11").attr("data-x", "620"),
                  $(".text12").attr("data-x", "620"),
                  $(".caption3").attr("data-voffset", "-100"),
                  $(".regBadge1").attr("data-x", "620"),
                  $(".regBadge2").attr("data-x", "620"),
                  $(".regBadge2").attr("data-y", "400"),
                  $(".regBadge2").attr("data-x", "620"),
                  $(".regBadge3").attr("data-x", "620"),
                  $(".regBadge4").attr("data-x", "620"),
                  $(".regBadge4").attr("data-y", "280"))
                : jQuery(window).width() < 1368 && jQuery(window).width() >= 1290
                ? ($(".slideContent").attr("data-hoffset", "-200"),
                  $(".slideImg").attr("style", "width: 49vw !important;height:auto !important;"),
                  $(".badgeSize").attr("style", "width:20vw !important;"),
                  $(".caption1").attr("data-x", "620"),
                  $(".caption2").attr("data-x", "620"),
                  $(".caption3").attr("data-x", "620"),
                  $(".caption4").attr("data-x", "620"),
                  $(".text11").attr("data-x", "620"),
                  $(".text12").attr("data-x", "620"),
                  $(".caption3").attr("data-voffset", "-100"),
                  $(".regBadge1").attr("data-x", "620"),
                  $(".regBadge2").attr("data-y", "400"),
                  $(".regBadge2").attr("data-x", "620"),
                  $(".regBadge3").attr("data-x", "620"),
                  $(".regBadge4").attr("data-x", "620"),
                  $(".regBadge4").attr("data-y", "280"))
                : jQuery(window).width() < 1445 && jQuery(window).width() >= 1364
                ? ($(".slideContent").attr("data-hoffset", "-240"),
                  $(".slideImg").attr("style", "width: 48vw !important;height:auto !important;"),
                  $(".badgeSize").attr("style", "width:20vw !important;"),
                  $(".text11").attr("data-x", "610"),
                  $(".text12").attr("data-x", "610"),
                  $(".caption1").attr("data-x", "610"),
                  $(".caption2").attr("data-x", "610"),
                  $(".caption3").attr("data-x", "610"),
                  $(".caption4").attr("data-x", "610"),
                  $(".caption3").attr("data-voffset", "-130"),
                  $(".regBadge2").attr("data-y", "400"),
                  $(".regBadge2").attr("data-x", "610"),
                  $(".regBadge3").attr("data-x", "610"),
                  $(".regBadge4").attr("data-y", "280"))
                : jQuery(window).width() < 1680 && jQuery(window).width() >= 1446
                ? ($(".slideContent").attr("data-hoffset", "-300"),
                  $(".slideContent").attr("data-y", "50"),
                  $(".slideImg").attr("style", "width: 48vw !important;height:auto !important;"),
                  $(".badgeSize").attr("style", "width:22vw !important;"),
                  $(".text11").attr("data-x", "650"),
                  $(".text12").attr("data-x", "650"),
                  $(".caption1").attr("data-x", "650"),
                  $(".caption2").attr("data-x", "650"),
                  $(".caption3").attr("data-x", "650"),
                  $(".caption4").attr("data-x", "650"),
                  $(".caption3").attr("data-voffset", "-130"),
                  $(".regBadge1").attr("data-x", "650"),
                  $(".regBadge2").attr("data-y", "400"),
                  $(".regBadge2").attr("data-x", "650"),
                  $(".regBadge3").attr("data-x", "650"),
                  $(".regBadge4").attr("data-x", "650"),
                  $(".regBadge4").attr("data-y", "280"))
                : jQuery(window).width() < 1690 && jQuery(window).width() >= 1611 && jQuery(window).height() <= 1060
                ? ($(".slideContent").attr("data-hoffset", "-420"),
                 $(".slideContent").attr("data-y", "10"), 
                 $(".slideImg").attr("style", "width: 55vw !important;height:50vh !important;"),
                  $(".caption2").attr("data-x", "940"))
                : jQuery(window).width() < 1921 && jQuery(window).width() >= 1611
                ? ($(".slideContent").attr("data-hoffset", "-495"),
                  $(".slideContent").attr("data-voffset", "-30"),
                  $(".slideContent").attr("data-y", "30"),
                  $(".slideImg").attr("style", "width: 47vw !important;height:auto !important;"),
                  $(".caption2").attr("data-x", "940"),
                  $(".badgeSize").attr("style", "width:20vw !important;"),
                  $(".text12").attr("data-x", "620"),
                  $(".caption1").attr("data-x", "620"),
                  $(".caption2").attr("data-x", "620"),
                  $(".caption3").attr("data-x", "620"),
                  $(".caption4").attr("data-x", "620"),
                  $(".caption3").attr("data-voffset", "-130"),
                  $(".regBadge1").attr("data-x", "620"),
                  $(".regBadge2").attr("data-y", "400"),
                  $(".regBadge2").attr("data-x", "620"),
                  $(".regBadge3").attr("data-x", "620"),
                  $(".regBadge4").attr("data-x", "620"),
                  $(".regBadge4").attr("data-y", "280"))
                : ($(".slideContent").attr("data-hoffset", "-520"),
                  $(".slideContent").attr("data-voffset", "-30"),
                  $(".slideContent").attr("data-y", "30"),
                  $(".slideImg").attr("style", "width: 47vw !important;height:auto !important;"),
                  $(".caption2").attr("data-x", "940"),
                  $(".badgeSize").attr("style", "width:25vw !important;"),
                  $(".text11").attr("data-x", "650"),
                  $(".text12").attr("data-x", "620"),
                  $(".caption1").attr("data-x", "650"),
                  $(".caption2").attr("data-x", "650"),
                  $(".caption3").attr("data-x", "650"),
                  $(".caption4").attr("data-x", "650"),
                  $(".caption3").attr("data-voffset", "-130"),
                  $(".regBadge1").attr("data-x", "650"),
                  $(".regBadge2").attr("data-y", "400"),
                  $(".regBadge2").attr("data-x", "650"),
                  $(".regBadge3").attr("data-x", "650"),
                  $(".regBadge4").attr("data-x", "650"),
                  $(".regBadge4").attr("data-y", "280")),
                jQuery(document).width();
        })
        .trigger("resize");
});
